# -*- coding: utf-8 -*-
{
    "name": "odoo-ngo",
    "summary": """""",
    "description": """Volunteers ngo modul""",
    "author": "Muhammed Aba",
    "website": "http://www.yourcompany.com",
    "version": "0.1",
    "depends": ["base", "contacts", "event", "base_address_city"],
    "installable": True,
    "sequence": -100,
    "application": True,
    "data": [
        # "data/event.skills.csv",
        "security\ir.model.access.csv",
        "views\menu.xml",
        "views\partner_view.xml",
        # "views\mail_template.xml",
        # "views\\volunteer_types_view.xml",
        "views\\volunteer_skills_view.xml",
        "views\\academy.xml",
        # "views\event_skills_view.xml",
        # "views\event_view.xml",
        "views\web_login_view.xml",
        # "views\orn.xml",
        # "views\member_types_view.xml",
        "views\website_form.xml",
        # "views\\branches_view.xml",
        "views\\ngo_city.xml",
        "views\\ngo_country.xml",
        "views\\ngo_branch.xml",
    ],
    "demo": [],
    "assets": {
        "web.assets_frontend": [
            "ngo-modul/static/src/js/branches.js",
            "ngo-modul/static/src/css/custom_styles.css",
        ],
    },
    "license": "LGPL-3",
}
