# -*- coding: utf-8 -*-
{
    "name": "odoo-ngo",
    "summary": """""",
    "description": """Volunteers ngo modul""",
    "author": "Muhammed Aba",
    "website": "http://www.yourcompany.com",
    "version": "0.1",
    "depends": ["base", "contacts", "event"],
    "installable": True,
    "sequence": -100,
    "application": True,
    "data": [
        "data/volunteer.skills.csv",
        # "data/event.skills.csv",
        "security\ir.model.access.csv",
        "views\menu.xml",
        "views\partner_view.xml",
        # "views\\volunteer_types_view.xml",
        "views\\volunteer_skills_view.xml",
        "views\event_skills_view.xml",
        "views\event_view.xml",
        "views\web_login_view.xml",
        # "views\donor_types_view.xml",
        # "views\website_form.xml",
    ],
    "demo": [],
    "license": "LGPL-3",
}
